services:
  kafka-ui:
    image: provectuslabs/kafka-ui:v0.7.2
    container_name: kafka-ui
    ports:
      - "${KAFKA_UI_PORT:-8080}:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: ${KAFKA_CLUSTER_NAME:-default}
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: ${KAFKA_BOOTSTRAP_SERVERS}
      KAFKA_CLUSTERS_0_PROPERTIES_SECURITY_PROTOCOL: ${KAFKA_PROPERTIES_SECURITY_PROTOCOL:-PLAINTEXT}
      KAFKA_CLUSTERS_0_PROPERTIES_SASL_MECHANISM: ${KAFKA_PROPERTIES_SASL_MECHANISM:-}
      KAFKA_CLUSTERS_0_PROPERTIES_SASL_JAAS_CONFIG: ${KAFKA_SASL_JAAS_CONFIG:-}
      DYNAMIC_CONFIG_ENABLED: "true"
    restart: unless-stopped
